In [2]:
import pandas as pd
messages = pd.read_csv(r'Datasets/dataset.csv')
messages.head()

  label                                               text
0  Spam  viiiiiiagraaaa\nonly for the ones that want to...
1   Ham  got ice thought look az original message ice o...
2  Spam  yo ur wom an ne eds an escapenumber in ch ma n...
3  Spam  start increasing your odds of success & live s...
4   Ham  author jra date escapenumber escapenumber esca...

In [3]:
# Data Cleaning and Preprocessing
import re
import nltk
# nltk.download('stopwords')

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [5]:
corpus=[]
for i in range(len(messages[:500])):
    review = re.sub('[^a-zA-Z]',' ',messages['text'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [6]:
corpus

['viiiiiiagraaaa one want make scream prodigi scrawni crow defin upgrad spongi balboa dither moiseyev schumann varieg ponc berni cox angel impass circul impend miscellani chalkboard whizz pend armenian cutlet ware makeshift fletch dispel crest cadet dovetail rapproch gerri bayreuth selectman wilmington tuttl alchemi itt bullyboy caan',
 'got ice thought look az origin messag ice oper mailto iceoper intcx com sent friday octob escapenumb escapenumb escapenumb escapenumb pm subject escapelong amend particip agreement dear particip receiv email identifi compani user administr legal counsel signatori escapelong particip agreement serv notic intercontinent intent amend agreement effect decemb escapenumb escapenumb relev document attach includ contact inform question thank escapelong inc',
 'yo ur wom ne ed escapenumb ch n b e th n f h er le arn h ow tu rn f ific ati on escapelong dy intern export ltd st regina escapenumb beliz citi beliz escapelong',
 'start increas odd success live sexual healthi easi impercept take take candi becom readi hour love modern safe way cover shame minut wait fda approv soft tab order packag discreetli privaci protect r emov',
 'author jra date escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb fri escapenumb jun escapenumb new revis escapenumb websvn http websvn samba org cgi bin viewcv cgi view rev root samba rev escapenumb log first part patch make appl life easier two stage make easi review context switch must look like gain root sy setgroup ngroup group becom id uid gid arrang order three call alway seen togeth next turn function jeremi modifi branch samba escapenumb escapenumb sourc smbd sec ctx c branch samba escapenumb escapenumb escapenumb sourc smbd sec ctx c changeset modifi branch samba escapenumb escapenumb sourc smbd sec ctx c branch samba escapenumb escapenumb sourc smbd sec ctx c escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb utc rev escapenumb branch samba escapenumb escapenumb sourc smbd sec ctx c escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb utc rev escapenumb escapenumb escapenumb escapenumb escapenumb debug nt user token dbgc class escapenumb token debug unix user token dbgc class escapenumb uid gid ngroup group start context switch gain root ifdef setgroup sy setgroup ngroup group endif becom id uid gid end context switch ctx p ut ngroup ngroup escapenumb escapenumb escapenumb escapenumb ctx p token null becom id uid gid ctx p ut uid uid ctx p ut gid gid escapenumb escapenumb escapenumb escapenumb sec ctx stack ndx gain root prev ctx p sec ctx stack sec ctx stack ndx start context switch gain root ifdef setgroup sy setgroup prev ctx p ut ngroup prev ctx p ut group endif becom id prev ctx p ut uid prev ctx p ut gid end context switch updat current user stuff modifi branch samba escapenumb escapenumb escapenumb sourc smbd sec ctx c branch samba escapenumb escapenumb escapenumb sourc smbd sec ctx c escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb utc rev escapenumb branch samba escapenumb escapenumb escapenumb sourc smbd sec ctx c escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb utc rev escapenumb escapenumb escapenumb escapenumb escapenumb debug nt user token dbgc class escapenumb token debug unix user token dbgc class escapenumb uid gid ngroup group start context switch gain root ifdef setgroup sy setgroup ngroup group endif becom id uid gid end context switch ctx p ut ngroup ngroup escapenumb escapenumb escapenumb escapenumb ctx p token null becom id uid gid ctx p ut uid uid ctx p ut gid gid escapenumb escapenumb escapenumb escapenumb sec ctx stack ndx gain root prev ctx p sec ctx stack sec ctx stack ndx start context switch gain root ifdef setgroup sy setgroup prev ctx p ut ngroup prev ctx p ut group endif becom id prev ctx p ut uid prev ctx p ut gid end context switch updat current user stuff',
 'img src escapenumberd http loan co kr img email imgescapenumb gif width escapenumberd escapenumb height escapenumberd escapenumb border escapenumberd escapenumb img src escapenumberd http loan co kr img email imgescapenumb gif width escapenumberd escapenumb height escapenumberd escapenumb border escapenumberd escapenumb img src escapenumberd http loan co kr img email imgescapenumb gif width escapenumberd escapenumb height escapenumberd escapenumb border escapenumberd escapenumb img src escapenumberd http loan co kr img email imgescapenumb gif width escapenumberd escapenumb height escapenumberd escapenumb border escapenumberd escapenumb hkxtattw x ikybkwdowkikjgzgznk ybreilxqd qfr rrpcckwlipgog',
 'attach weekli deal report lex carrol enron east power market inc midwest origin',
 'version creat earlier afternoon use ena short form bilater confidenti agreement travi c mccullough enron north america corp escapenumb smith street eb escapenumb houston texa escapenumb phone escapenumb escapenumb escapenumb fax escapenumb escapenumb escapenumb',
 'pulp write print paper escapenumb escapenumb escapenumb welcom enron pulp write print paper news servic daili mail bring recent news headlin right inbox may also receiv daili servic specif follow area escapenumb recov contain packag escapenumb newsprint escapenumb lumber join list click comment feedback simpli repli email would like unsubscrib pulp write print paper news servic pleas scroll bottom email instruct thank enjoy content carter holt harvey post huge net loss march septemb period wausau mosine paper report escapenumberq earn escapenumb potlatch cite poor market condit report third quarter loss buckey break even third quarter escapenumb sale drop domtar report net quarterli sale rise escapenumb escapenumb billion net earn plummet georgia pacif report third quarter earn drop sale increas metsaliitto pulp mill project latvia may fall strike union lash finch pruyn set talk n mill pennsylvania center receiv escapenumb escapenumb toward print industri pollut reduct harri group add chuck schultz lead midwest forest industri team carter holt harvey post huge net loss march septemb period escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb agenc franc press wellington oct escapenumb escapenumb agenc franc press new zealand largest forest product compani carter holt harvey post net loss escapenumb million new zealand escapenumb escapenumb million dollar first half year said wednesday stori top page wausau mosine paper report escapenumberq earn escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb bw mosine wi busi wire octob escapenumb escapenumb wausau mosine paper corpor nyse wmo news today announc third quarter net earn escapenumb escapenumb million escapenumb escapenumb per share escapenumb percent escapenumb escapenumb million escapenumb escapenumb per share prior year sharpli net incom escapenumb escapenumb million escapenumb escapenumb per share second quarter escapenumb third quarter escapenumb earn includ stock incent credit escapenumb escapenumb per share compar credit less escapenumb escapenumb per share period last year expens escapenumb escapenumb per share second quarter escapenumb stori top page potlatch cite poor market condit report third quarter loss escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb bw spokan wash oct escapenumb escapenumb busi wire press releas potlatch corpor nyse pch today report poor market condit product substanti higher inter stori top page buckey break even third quarter escapenumb sale drop escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb bw memphi tenn oct escapenumb escapenumb press releas buckey technolog inc today announc net incom juli septemb escapenumb quarter break even estim septemb escapenumb earn warn buckey incom cumul effect chang account escapenumb escapenumb million quarter last year net sale escapenumb escapenumb million quarter end escapenumb quarter last year stori top page domtar report net quarterli sale rise escapenumb escapenumb billion net earn plummet escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb prnewswir montreal oct escapenumb escapenumb press releas domtar inc today announc net earn escapenumb million escapenumb escapenumb per common share third quarter escapenumb compar escapenumb million escapenumb escapenumb per common share correspond period escapenumb oper profit reach escapenumb million compar escapenumb million third quarter escapenumb net sale almost escapenumb escapenumb billion versu escapenumb million period last year stori top page georgia pacif report third quarter earn drop sale increas escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb prnewswir atlanta oct escapenumb escapenumb press releas georgia pacif corp nyse gp news today report third quarter escapenumb incom continu oper escapenumb million escapenumb cent dilut earn per share one time loss compar incom continu oper escapenumb million escapenumb cent dilut earn per share period last year compani incur one time escapenumb million pre tax loss escapenumb million tax loss escapenumb escapenumb dilut loss per share sale portion pulp paper facil domtar inc escapenumb escapenumb billion result third quarter escapenumb loss continu oper escapenumb million escapenumb cent dilut loss per share stori top page metsaliitto pulp mill project latvia may fall escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb helsingin sanomat oct escapenumb escapenumb helsingin sanomat larg new pulp mill plan latvia allow fell tree forest own latvian state say latvian minist agricultur ati slakteri announc mean project joint undertak finnish forest compani met liitto swedish forest compani dra latvian state may realis project would cost fim escapenumb escapenumb million us escapenumb million latvian state prepar provid guarante suppli raw materi met liitto satisfi guarante stori top page strike union lash finch pruyn set talk n mill escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb prnewswir glen fall n oct escapenumb escapenumb press releas union repres strike finch pruyn worker today lash finch pruyn letter compani sent escapenumb hourli employe announc perman replac worker strike sinc june escapenumb stori top page pennsylvania center receiv escapenumb escapenumb toward print industri pollut reduct escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb prnewswir pennsylvania depart environmen protect secretari announc escapenumb escapenumb electrotechnolog applic center northampton commun colleg harrisburg pa oct escapenumb escapenumb p stori top page harri group add chuck schultz lead midwest forest industri team escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb press releas seattl oct escapenumb escapenumb press releas consult engin firm harri group inc ad charl chuck schultz vice presid forest industri midwest region w stori top page unsubscrib pulp write print paper news click unsubscrib simpli send correspond email news report copyright respect author power forestweb',
 'stefan metz metzmach write stefan metz metzmach schrieb derrel lipman unwiredunivers com schrieb stefan metz metzmach write seem revis escapenumb merg branch http websvn samba org cgi bin viewcv cgi rev escapenumb view rev sorri think merg sambaescapenumb branch occur code use sambaescapenumb mayb better move sambaescapenumb instead libreplac libreplac provid replac readahead chang merg libreplac sambaescapenumb problem intend solv exist readahead function header declar would exist much sambaescapenumb sambaescapenumb even noth sambaescapenumb current use readahead pleas go ahead merg current work also configur test ad patch hi derel know initi problem test readahead function configur sambaescapenumb test prototyp also realli belong sambaescapenumb exactli lot function sambaescapenumb configur includ includ h ok attempt keep sambaescapenumb sambaescapenumb libreplac derrel',
 'hey life sound horribl busi figur worri thought get thing move sinc offici replac announc direct report london fernley sure spoken anxiou put announc enron europ phillip lord leav melissa step replac us sinc phillip alreadi place go would nice could least say go north america energi op someth even detail work sure want come meet commerci custom also never met delainey think mayb know frevert well enough plan come novemb first half work europ plan coordin brent we group frevert mayb meet peopl would love discuss monday fine sure today anoth crazi day know review john sherriff put per review per day penalti dept head review done august th cours holiday week day review hope help direct report problem talk today good weekend beth enron capit trade resourc corp salli beck beth apollo lon ect ect cc subject stuff crazi week pm finish project delainey got noon today cancel everyth calendar immers ever sinc patti gave messag home number around today leav apolog give earlier howev given immedi project think could call london time think e mail much better still realli crunch tomorrow morn mid year review must complet time ena offic chair staff meet tomorrow big push percentag complet rate ena meet two week ago unfinish review mine give direct report killer wrote three last night tyler went bed finish gave three review morn write tonight deliv tomorrow morn tri call way offic tomorrow morn car miss late afternoon houston time could call next week shape much better definit interest continu convers would love involv oper either catch car tomorrow morn talk monday',
 'think firewal would catch email freak origin messag chad knipe mailto knipeescapenumb msn com sent tuesday februari escapenumb escapenumb escapenumb escapenumb pm chet fenner feder erik wollam corrier cox internet com c r zander att net joe park john chamber brian constantin c r zander subject locat man night open e mail jerki entitl monster facial blast think firewal would catch origin messag fenner chet sent tuesday februari escapenumb escapenumb escapenumb escapenumb pm feder erwollam corrier cox internet com c k fenner chet c r zander att net joe park john chamber bisi com brianc c r zander subject locat man night either way sound like deal w axi evil restaur chain guy let admit old get much except zander caus hotti realli care food meet gold cup origin messag feder mailto lawfed msn com sent tuesday februari escapenumb escapenumb escapenumb escapenumb pm erwollam corrier cox internet com c k chet fenner c r zander att net joe park john chamber bisi com brianc c r zander subject locat man night ass grape see monkey eat grape especi airlin drive nice part town hey new al qaeda restaur telephon road heard good sleeper cell chili hhmmm hmmm good splash taliban relish origin messag erik wollam sent tuesday februari escapenumb escapenumb escapenumb escapenumb pm corrier cox internet com knipeescapenumb msn com chet fenner bmc com c r zander att net joe park enron com john chamber bisi com brianc saltgrass com lawfed msn com c r zander worldnet att net subject locat man night plan thursday escapenumb escapenumb escapenumb restraunt idenitifi z pig pleas provid direct time escapenumb escapenumb e brian constantin erik wollam subject man night date wed escapenumb feb escapenumb escapenumb escapenumb escapenumb escapenumb horribl liquid pud accompani incess stomach cramp fever gener malais last week along w ass grape needless say unavail comment howev back full health grape vanish would love men vote go new secret dive zander howl call tampico seafood mexican seafood type joint airlin drive close farmer market z say unfuckinbeliev im origin messag erik wollam mailto erwollam hotmail com sent wednesday februari escapenumb escapenumb escapenumb escapenumb pm bcorrier cox internet com knipeescapenumb msn com chet fenner bmc com c r zander att net joe park enron com john chamber bisi com brian constantin lawfed msn com c r zander worldnet att net subject man night men hunt season work season email thread gone one talk one anoth wrong therefor propos man night februari escapenumberth escapenumb locat yet determin toni mexican food ella e chat friend onlin tri msn messeng http messeng msn com msn photo easiest way share print photo http photo msn com support worldwid aspx',
 'luckyday lotteri intern intern promot prize award dept websit www luckyday nl ref mli escapenumb ilgiescapenumb escapenumb batch ipd escapenumb escapenumb ptnl sir madam pleas inform result lotteri winner intern program held escapenumberth juli escapenumb e mail address attach ticket number escapenumb escapenumb serial number escapenumb escapenumb drew lucki number escapenumb escapenumb escapenumb escapenumb escapenumb escapenumb consequ escapenumberrd categori therefor approv sum pay us escapenumb escapenumb six hundr twenti three thousand unit state dollar congratul due mix number name ask keep win inform confidenti till claim process prize money remit part secur proto col avoid doubl claim unwarr abus program particip particip select comput ballot system drawn escapenumb escapenumb escapenumb compani escapenumb escapenumb escapenumb individu email address name world promot program take place annual hope part win take part next year usdescapenumb million intern lotteri file claim pleas contact fiduci agent dr free de veen fortuneg agenc tel escapenumb escapenumb escapenumb escapenumb fax escapenumb escapenumb escapenumb escapenumb e mail escapelong netscap net note win must claim later escapenumberth juli escapenumb date unclaim fund includ next stake pleas note order avoid unnecessari delay complic pleas rememb quot refer number batch number correspond furthermor chang address inform agent soon possibl congratul member staff thank part promot program note anybodi age escapenumb automat disqualifi sincer mr helen van hal lotteri coordin repli email luckyday winningaward nl escapelong netscap net',
 'ti pvc jgjrkwhr j p tc bxff cou roxli exgxj iryqhgno ljpi',
 'greet netherland intend take time unduli financi plea son late foreign affair minist feder republ zair dr pinga kasenda move write letter consid present circumst disclos detail manag escap netherland europ safeti mother two sister escap abidjan cote devoir settl chose escap netherland carri transfer deposit sum escapenumb escapenumbermillion financ institut made late father death present relev document sole beneficiari refus claim base age valid account transfer sum henc solicit assist provid outstand account transfer note requir make payment form mother reserv good amount miscellan expens might involv ofcours compens success complet transact pleas keep confidenti present refuge camp netherland routin restrict movement easili contact detail document wanami com thank anticip wanami kasenda use melhor sistema de busca da internet radar uol http www radaruol com br',
 'everyth need escapelong cialescapenumb sescapenumberft tescapenumberb vescapenumberagra sescapenumberft tescapenumberb cialescapenumb vescapenumberagra levescapenumbertra propecescapenumbera valescapenumberum xanescapenumberx ambescapenumberen zybescapenumbern atarescapenumberx atescapenumbervan carescapenumbersoma ultrescapenumberm escapelong lipescapenumbertor merescapenumberdia zocescapenumberr nescapenumberrvasc respect privaci guarante total anonym escapenumberrd visit us escapelong inc onlin http www caluke com',
 'dear custom secret lot onlin pharmaci cheat client sell fake drug order make extra profit search cheap gener drug web realli hard job often turn complet fruitless visit canadianpharmaci make much easier canadianpharmaci wide choic reliabl gener drug offer realli laughabl price canadianpharmaci save money high qualiti gener medic canada sincer megan gagn',
 'tana jone offic return thursday novemb escapenumb',

### Create Bag of Words

In [7]:
# Create BOW
from sklearn.feature_extraction.text import CountVectorizer
# for binary BOW enable binary=True
cv = CountVectorizer(max_features=2500,ngram_range=(1,2))

In [8]:
# Independent Feature
X=cv.fit_transform(corpus).toarray()

In [9]:
cv.vocabulary_

{'one': np.int64(1599),
 'want': np.int64(2393),
 'make': np.int64(1402),
 'defin': np.int64(584),
 'upgrad': np.int64(2342),
 'cox': np.int64(518),
 'angel': np.int64(90),
 'got': np.int64(1050),
 'thought': np.int64(2248),
 'look': np.int64(1368),
 'origin': np.int64(1616),
 'messag': np.int64(1454),
 'oper': np.int64(1604),
 'mailto': np.int64(1398),
 'com': np.int64(418),
 'sent': np.int64(2021),
 'friday': np.int64(1004),
 'octob': np.int64(1583),
 'escapenumb': np.int64(780),
 'pm': np.int64(1723),
 'subject': np.int64(2174),
 'escapelong': np.int64(775),
 'amend': np.int64(74),
 'particip': np.int64(1644),
 'agreement': np.int64(53),
 'dear': np.int64(571),
 'receiv': np.int64(1848),
 'email': np.int64(708),
 'identifi': np.int64(1158),
 'compani': np.int64(437),
 'user': np.int64(2352),
 'administr': np.int64(24),
 'legal': np.int64(1322),
 'counsel': np.int64(504),
 'serv': np.int64(2034),
 'notic': np.int64(1564),
 'intent': np.int64(1208),
 'effect': np.int64(693),
 'decemb': np.int64(576),
 'relev': np.int64(1871),
 'document': np.int64(633),
 'attach': np.int64(137),
 'includ': np.int64(1176),
 'contact': np.int64(475),
 'inform': np.int64(1188),
 'question': np.int64(1818),
 'thank': np.int64(2239),
 'inc': np.int64(1173),
 'origin messag': np.int64(1617),
 'com sent': np.int64(423),
 'sent friday': np.int64(2022),
 'friday octob': np.int64(1005),
 'octob escapenumb': np.int64(1584),
 'escapenumb escapenumb': np.int64(791),
 'escapenumb pm': np.int64(813),
 'pm subject': np.int64(1724),
 'decemb escapenumb': np.int64(577),
 'ed': np.int64(679),
 'ch': np.int64(359),
 'th': np.int64(2238),
 'intern': np.int64(1213),
 'ltd': np.int64(1385),
 'st': np.int64(2123),
 'citi': np.int64(390),
 'start': np.int64(2132),
 'increas': np.int64(1178),
 'success': np.int64(2180),
 'live': np.int64(1351),
 'easi': np.int64(671),
 'take': np.int64(2208),
 'becom': np.int64(197),
 'readi': np.int64(1840),
 'hour': np.int64(1130),
 'love': np.int64(1379),
 'safe': np.int64(1947),
 'way': np.int64(2401),
 'cover': np.int64(516),
 'minut': np.int64(1476),
 'wait': np.int64(2388),
 'approv': np.int64(110),
 'soft': np.int64(2084),
 'order': np.int64(1610),
 'packag': np.int64(1633),
 'privaci': np.int64(1772),
 'protect': np.int64(1801),
 'author': np.int64(148),
 'date': np.int64(555),
 'jun': np.int64(1265),
 'new': np.int64(1541),
 'revis': np.int64(1915),
 'websvn': np.int64(2407),
 'http': np.int64(1146),
 'samba': np.int64(1955),
 'org': np.int64(1611),
 'cgi': np.int64(358),
 'bin': np.int64(240),
 'view': np.int64(2379),
 'rev': np.int64(1909),
 'root': np.int64(1934),
 'log': np.int64(1362),
 'first': np.int64(961),
 'part': np.int64(1642),
 'appl': np.int64(103),
 'life': np.int64(1335),
 'two': np.int64(2313),
 'stage': np.int64(2126),
 'review': np.int64(1914),
 'context': np.int64(481),
 'switch': np.int64(2204),
 'must': np.int64(1511),
 'like': np.int64(1337),
 'gain': np.int64(1026),
 'ngroup': np.int64(1550),
 'group': np.int64(1064),
 'id': np.int64(1155),
 'uid': np.int64(2321),
 'gid': np.int64(1035),
 'arrang': np.int64(118),
 'three': np.int64(2250),
 'call': np.int64(292),
 'alway': np.int64(72),
 'seen': np.int64(2006),
 'togeth': np.int64(2265),
 'next': np.int64(1547),
 'turn': np.int64(2312),
 'function': np.int64(1016),
 'jeremi': np.int64(1249),
 'modifi': np.int64(1484),
 'branch': np.int64(261),
 'sourc': np.int64(2097),
 'sec': np.int64(1990),
 'ctx': np.int64(534),
 'utc': np.int64(2355),
 'token': np.int64(2266),
 'class': np.int64(393),
 'end': np.int64(715),
 'ut': np.int64(2354),
 'stack': np.int64(2124),
 'prev': np.int64(1760),
 'updat': np.int64(2340),
 'current': np.int64(539),
 'stuff': np.int64(2172),
 'date escapenumb': np.int64(557),
 'jun escapenumb': np.int64(1266),
 'escapenumb new': np.int64(807),
 'samba org': np.int64(1957),
 'rev escapenumb': np.int64(1910),
 'look like': np.int64(1370),
 'modifi branch': np.int64(1485),
 'branch samba': np.int64(262),
 'samba escapenumb': np.int64(1956),
 'escapenumb sourc': np.int64(820),
 'sec ctx': np.int64(1991),
 'escapenumb utc': np.int64(825),
 'utc rev': np.int64(2356),
 'ctx ut': np.int64(535),
 'prev ctx': np.int64(1761),
 'src': np.int64(2119),
 'escapenumberd': np.int64(833),
 'loan': np.int64(1357),
 'co': np.int64(405),
 'escapenumberd escapenumb': np.int64(834),
 'weekli': np.int64(2414),
 'deal': np.int64(570),
 'report': np.int64(1881),
 'enron': np.int64(734),
 'power': np.int64(1742),
 'market': np.int64(1417),
 'midwest': np.int64(1464),
 'power market': np.int64(1743),
 'version': np.int64(2371),
 'creat': np.int64(520),
 'earlier': np.int64(667),
 'afternoon': np.int64(43),
 'use': np.int64(2351),
 'short': np.int64(2054),
 'form': np.int64(988),
 'confidenti': np.int64(459),
 'north': np.int64(1559),
 'america': np.int64(75),
 'corp': np.int64(496),
 'smith': np.int64(2082),
 'street': np.int64(2161),
 'eb': np.int64(674),
 'houston': np.int64(1133),
 'texa': np.int64(2236),
 'phone': np.int64(1686),
 'fax': np.int64(917),
 'north america': np.int64(1560),
 'escapenumb smith': np.int64(819),
 'phone escapenumb': np.int64(1687),
 'escapenumb fax': np.int64(793),
 'fax escapenumb': np.int64(918),
 'write': np.int64(2466),
 'print': np.int64(1769),
 'paper': np.int64(1640),
 'welcom': np.int64(2416),
 'news': np.int64(1543),
 'servic': np.int64(2036),
 'daili': np.int64(546),
 'mail': np.int64(1392),
 'bring': np.int64(268),
 'recent': np.int64(1849),
 'right': np.int64(1918),
 'may': np.int64(1435),
 'also': np.int64(69),
 'specif': np.int64(2104),
 'follow': np.int64(979),
 'area': np.int64(114),
 'recov': np.int64(1853),
 'contain': np.int64(477),
 'join': np.int64(1255),
 'list': np.int64(1344),
 'click': np.int64(398),
 'comment': np.int64(427),
 'feedback': np.int64(932),
 'simpli': np.int64(2066),
 'repli': np.int64(1880),
 'would': np.int64(2462),
 'unsubscrib': np.int64(2339),
 'pleas': np.int64(1713),
 'bottom': np.int64(254),
 'instruct': np.int64(1203),
 'enjoy': np.int64(731),
 'content': np.int64(479),
 'carter': np.int64(312),
 'post': np.int64(1736),
 'huge': np.int64(1149),
 'net': np.int64(1534),
 'loss': np.int64(1375),
 'march': np.int64(1411),
 'septemb': np.int64(2030),
 'period': np.int64(1672),
 'earn': np.int64(668),
 'cite': np.int64(389),
 'poor': np.int64(1730),
 'condit': np.int64(454),
 'third': np.int64(2244),
 'quarter': np.int64(1816),
 'break': np.int64(264),
 'even': np.int64(855),
 'sale': np.int64(1951),
 'drop': np.int64(654),
 'rise': np.int64(1921),
 'billion': np.int64(239),
 'pacif': np.int64(1631),
 'project': np.int64(1793),
 'fall': np.int64(906),
 'union': np.int64(2329),
 'set': np.int64(2038),
 'talk': np.int64(2211),
 'center': np.int64(331),
 'toward': np.int64(2281),
 'industri': np.int64(1185),
 'reduct': np.int64(1857),
 'harri': np.int64(1087),
 'add': np.int64(21),
 'chuck': np.int64(384),
 'lead': np.int64(1314),
 'forest': np.int64(987),
 'team': np.int64(2220),
 'agenc': np.int64(47),
 'press': np.int64(1756),
 'oct': np.int64(1581),
 'largest': np.int64(1299),
 'product': np.int64(1783),
 'million': np.int64(1469),
 'dollar': np.int64(634),
 'half': np.int64(1078),
 'year': np.int64(2488),
 'said': np.int64(1948),
 'wednesday': np.int64(2409),
 'stori': np.int64(2156),
 'top': np.int64(2272),
 'page': np.int64(1634),
 'wi': np.int64(2430),
 'busi': np.int64(280),
 'wire': np.int64(2441),
 'corpor': np.int64(498),
 'today': np.int64(2263),
 'announc': np.int64(92),
 'per': np.int64(1663),
 'share': np.int64(2045),
 'percent': np.int64(1667),
 'prior': np.int64(1770),
 'sharpli': np.int64(2048),
 'incom': np.int64(1177),
 'second': np.int64(1993),
 'stock': np.int64(2150),
 'credit': np.int64(523),
 'compar': np.int64(442),
 'less': np.int64(1326),
 'last': np.int64(1301),
 'expens': np.int64(878),
 'releas': np.int64(1870),
 'substanti': np.int64(2179),
 'higher': np.int64(1108),
 'technolog': np.int64(2224),
 'juli': np.int64(1263),
 'estim': np.int64(847),
 'warn': np.int64(2395),
 'chang': np.int64(367),
 'account': np.int64(7),
 'common': np.int64(435),
 'correspond': np.int64(500),
 'profit': np.int64(1789),
 'reach': np.int64(1834),
 'almost': np.int64(66),
 'atlanta': np.int64(135),
 'continu': np.int64(482),
 'cent': np.int64(330),
 'time': np.int64(2257),
 'pre': np.int64(1747),
 'tax': np.int64(2216),
 'portion': np.int64(1732),
 'facil': np.int64(898),
 'result': np.int64(1901),
 'larg': np.int64(1297),
 'plan': np.int64(1706),
 'allow': np.int64(65),
 'fell': np.int64(936),
 'tree': np.int64(2303),
 'own': np.int64(1627),
 'state': np.int64(2136),
 'say': np.int64(1972),
 'mean': np.int64(1440),
 'joint': np.int64(1256),
 'met': np.int64(1455),
 'cost': np.int64(501),
 'us': np.int64(2345),
 'prepar': np.int64(1753),
 'provid': np.int64(1803),
 'guarante': np.int64(1070),
 'suppli': np.int64(2193),
 'materi': np.int64(1425),
 'repres': np.int64(1882),
 'worker': np.int64(2456),
 'letter': np.int64(1329),
 'employe': np.int64(712),
 'replac': np.int64(1879),
 'sinc': np.int64(2067),
 'june': np.int64(1267),
 'depart': np.int64(594),
 'secretari': np.int64(1996),
 'applic': np.int64(105),
 'commun': np.int64(436),
 'colleg': np.int64(414),
 'pa': np.int64(1630),
 'seattl': np.int64(1989),
 'consult': np.int64(473),
 'engin': np.int64(729),
 'firm': np.int64(960),
 'ad': np.int64(20),
 'charl': np.int64(370),
 'vice': np.int64(2376),
 'presid': np.int64(1755),
 'region': np.int64(1862),
 'send': np.int64(2017),
 'copyright': np.int64(490),
 'respect': np.int64(1894),
 'would like': np.int64(2463),
 'market condit': np.int64(1418),
 'third quarter': np.int64(2246),
 'quarter escapenumb': np.int64(1817),
 'escapenumb billion': np.int64(784),
 'oct escapenumb': np.int64(1582),
 'escapenumb million': np.int64(802),
 'first half': np.int64(962),
 'stori top': np.int64(2157),
 'top page': np.int64(2273),
 'million escapenumb': np.int64(1471),
 'escapenumb per': np.int64(808),
 'per share': np.int64(1666),
 'escapenumb percent': np.int64(809),
 'net incom': np.int64(1535),
 'second quarter': np.int64(1994),
 'last year': np.int64(1304),
 'press releas': np.int64(1757),
 'septemb escapenumb': np.int64(2031),
 'time escapenumb': np.int64(2259),
 'us escapenumb': np.int64(2347),
 'june escapenumb': np.int64(1268),
 'vice presid': np.int64(2377),
 'seem': np.int64(2005),
 'merg': np.int64(1452),
 'sorri': np.int64(2095),
 'think': np.int64(2243),
 'sambaescapenumb': np.int64(1958),
 'occur': np.int64(1580),
 'code': np.int64(407),
 'mayb': np.int64(1438),
 'better': np.int64(226),
 'move': np.int64(1499),
 'instead': np.int64(1201),
 'problem': np.int64(1778),
 'intend': np.int64(1206),
 'exist': np.int64(874),
 'much': np.int64(1508),
 'noth': np.int64(1563),
 'go': np.int64(1042),
 'ahead': np.int64(54),
 'work': np.int64(2455),
 'test': np.int64(2233),
 'hi': np.int64(1105),
 'know': np.int64(1288),
 'initi': np.int64(1191),
 'realli': np.int64(1846),
 'exactli': np.int64(864),
 'lot': np.int64(1377),
 'ok': np.int64(1597),
 'attempt': np.int64(139),
 'keep': np.int64(1273),
 'pleas go': np.int64(1717),
 'hey': np.int64(1104),
 'sound': np.int64(2096),
 'figur': np.int64(945),
 'worri': np.int64(2460),
 'get': np.int64(1032),
 'thing': np.int64(2242),
 'offici': np.int64(1589),
 'direct': np.int64(622),
 'london': np.int64(1364),
 'sure': np.int64(2197),
 'put': np.int64(1813),
 'europ': np.int64(852),
 'phillip': np.int64(1685),
 'leav': np.int64(1319),
 'step': np.int64(2145),
 'alreadi': np.int64(68),
 'place': np.int64(1705),
 'nice': np.int64(1551),
 'could': np.int64(502),
 'least': np.int64(1318),
 'energi': np.int64(717),
 'someth': np.int64(2092),
 'detail': np.int64(613),
 'come': np.int64(425),
 'meet': np.int64(1447),
 'commerci': np.int64(429),
 'custom': np.int64(542),
 'never': np.int64(1540),
 'well': np.int64(2417),
 'enough': np.int64(732),
 'novemb': np.int64(1567),
 'coordin': np.int64(488),
 'peopl': np.int64(1662),
 'discuss': np.int64(628),
 'monday': np.int64(1486),
 'fine': np.int64(957),
 'anoth': np.int64(94),
 'day': np.int64(561),
 'john': np.int64(1253),
 'dept': np.int64(597),
 'head': np.int64(1089),
 'done': np.int64(638),
 'august': np.int64(146),
 'cours': np.int64(514),
 'holiday': np.int64(1121),
 'week': np.int64(2410),
 'hope': np.int64(1123),
 'help': np.int64(1099),
 'good': np.int64(1048),
 'weekend': np.int64(2413),
 'capit': np.int64(304),
 'trade': np.int64(2284),
 'resourc': np.int64(1893),
 'salli': np.int64(1952),
 'ect': np.int64(677),
 'cc': np.int64(321),
 'finish': np.int64(958),
 'cancel': np.int64(299),
 'everyth': np.int64(862),
 'ever': np.int64(858),
 'gave': np.int64(1028),
 'home': np.int64(1122),
 'number': np.int64(1571),
 'around': np.int64(117),
 'give': np.int64(1037),
 'howev': np.int64(1139),
 'given': np.int64(1038),
 'immedi': np.int64(1168),
 'still': np.int64(2149),
 'tomorrow': np.int64(2269),
 'morn': np.int64(1496),
 'mid': np.int64(1462),
 'complet': np.int64(446),
 'offic': np.int64(1587),
 'staff': np.int64(2125),
 'big': np.int64(234),
 'push': np.int64(1812),
 'percentag': np.int64(1668),
 'rate': np.int64(1829),
 'ago': np.int64(51),
 'wrote': np.int64(2469),
 'night': np.int64(1552),
 'went': np.int64(2418),
 'bed': np.int64(198),
 'deliv': np.int64(589),
 'tri': np.int64(2304),
 'car': np.int64(306),
 'miss': np.int64(1478),
 'late': np.int64(1305),
 'definit': np.int64(585),
 'interest': np.int64(1211),
 'convers': np.int64(487),
 'involv': np.int64(1225),
 'either': np.int64(697),
 'catch': np.int64(316),
 'ect ect': np.int64(678),
 'cc subject': np.int64(324),
 'two week': np.int64(2315),
 'week ago': np.int64(2411),
 'next week': np.int64(1549),
 'msn': np.int64(1506),
 'tuesday': np.int64(2311),
 'februari': np.int64(925),
 'feder': np.int64(928),
 'internet': np.int64(1214),
 'zander': np.int64(2498),
 'att': np.int64(136),
 'joe': np.int64(1252),
 'park': np.int64(1641),
 'brian': np.int64(265),
 'locat': np.int64(1360),
 'man': np.int64(1406),
 'open': np.int64(1603),
 'chain': np.int64(362),
 'guy': np.int64(1075),
 'let': np.int64(1327),
 'admit': np.int64(25),
 'old': np.int64(1598),
 'except': np.int64(867),
 'caus': np.int64(319),
 'care': np.int64(308),
 'food': np.int64(981),
 'see': np.int64(2003),
 'eat': np.int64(673),
 'especi': np.int64(843),
 'drive': np.int64(653),
 'town': np.int64(2282),
 'al': np.int64(58),
 'telephon': np.int64(2227),
 'road': np.int64(1927),
 'heard': np.int64(1092),
 'cell': np.int64(329),
 'thursday': np.int64(2253),
 'wed': np.int64(2408),
 'feb': np.int64(923),
 'liquid': np.int64(1343),
 'gener': np.int64(1030),
 'along': np.int64(67),
 'back': np.int64(161),
 'full': np.int64(1012),
 'health': np.int64(1090),
 'men': np.int64(1450),
 'vote': np.int64(2387),
 'secret': np.int64(1995),
 'type': np.int64(2319),
 'close': np.int64(401),
 'im': np.int64(1165),
 'season': np.int64(1987),
 'gone': np.int64(1047),
 'wrong': np.int64(2468),
 'therefor': np.int64(2240),
 'propos': np.int64(1799),
 'escapenumberth': np.int64(841),
 'yet': np.int64(2493),
 'determin': np.int64(614),
 'friend': np.int64(1006),
 'onlin': np.int64(1600),
 'photo': np.int64(1688),
 'support': np.int64(2195),
 'worldwid': np.int64(2459),
 'msn com': np.int64(1507),
 'sent tuesday': np.int64(2025),
 'februari escapenumb': np.int64(926),
 'enron com': np.int64(739),
 'feb escapenumb': np.int64(924),
 'last week': np.int64(1303),
 'sent wednesday': np.int64(2026),
 'escapenumberth escapenumb': np.int64(842),
 'promot': np.int64(1796),
 'prize': np.int64(1775),
 'award': np.int64(155),
 'websit': np.int64(2406),
 'www': np.int64(2471),
 'program': np.int64(1790),
 'held': np.int64(1096),
 'address': np.int64(23),
 'ticket': np.int64(2254),
 'drew': np.int64(652),
 'consequ': np.int64(466),
 'escapenumberrd': np.int64(839),
 'categori': np.int64(317),
 'sum': np.int64(2186),
 'pay': np.int64(1658),
 'six': np.int64(2073),
 'hundr': np.int64(1151),
 'thousand': np.int64(2249),
 'unit': np.int64(2331),
 'due': np.int64(657),
 'mix': np.int64(1480),
 'name': np.int64(1516),
 'ask': np.int64(124),
 'win': np.int64(2436),
 'claim': np.int64(392),
 'process': np.int64(1781),
 'money': np.int64(1489),
 'secur': np.int64(2000),
 'avoid': np.int64(153),
 'doubl': np.int64(641),
 'select': np.int64(2008),
 'comput': np.int64(451),
 'ballot': np.int64(169),
 'system': np.int64(2206),
 'individu': np.int64(1184),
 'world': np.int64(2458),
 'annual': np.int64(93),
 'file': np.int64(946),
 'agent': np.int64(48),
 'free': np.int64(1002),
 'de': np.int64(568),
 'tel': np.int64(2225),
 'note': np.int64(1562),
 'later': np.int64(1306),
 'fund': np.int64(1017),
 'stake': np.int64(2127),
 'delay': np.int64(587),
 'complic': np.int64(448),
 'rememb': np.int64(1875),
 'quot': np.int64(1822),
 'refer': np.int64(1858),
 'soon': np.int64(2093),
 'possibl': np.int64(1735),
 'member': np.int64(1448),
 'age': np.int64(46),
 'sincer': np.int64(2068),
 'mr': np.int64(1501),
 'mail address': np.int64(1393),
 'number escapenumb': np.int64(1572),
 'unit state': np.int64(2332),
 'email address': np.int64(709),
 'pleas contact': np.int64(1716),
 'tel escapenumb': np.int64(2226),
 'escapenumb date': np.int64(786),
 'soon possibl': np.int64(2094),
 'financi': np.int64(951),
 'foreign': np.int64(986),
 'affair': np.int64(40),
 'consid': np.int64(467),
 'present': np.int64(1754),
 'disclos': np.int64(625),
 'manag': np.int64(1407),
 'escap': np.int64(774),
 'carri': np.int64(311),
 'transfer': np.int64(2294),
 'deposit': np.int64(596),
 'financ': np.int64(950),
 'institut': np.int64(1202),
 'made': np.int64(1390),
 'death': np.int64(572),
 'sole': np.int64(2087),
 'base': np.int64(179),
 'valid': np.int64(2362),
 'solicit': np.int64(2088),
 'assist': np.int64(129),
 'outstand': np.int64(1623),
 'requir': np.int64(1888),
 'payment': np.int64(1659),
 'reserv': np.int64(1891),
 'amount': np.int64(79),
 'might': np.int64(1465),
 'compens': np.int64(443),
 'transact': np.int64(2293),
 'easili': np.int64(672),
 'anticip': np.int64(97),
 'da': np.int64(544),
 'br': np.int64(257),
 'http www': np.int64(1148),
 'need': np.int64(1530),
 'total': np.int64(2278),
 'visit': np.int64(2381),
 'client': np.int64(399),
 'sell': np.int64(2011),
 'drug': np.int64(655),
 'extra': np.int64(890),
 'search': np.int64(1986),
 'cheap': np.int64(372),
 'web': np.int64(2404),
 'hard': np.int64(1086),
 'job': np.int64(1251),
 'often': np.int64(1590),
 'canadianpharmaci': np.int64(298),
 'wide': np.int64(2431),
 'choic': np.int64(380),
 'reliabl': np.int64(1873),
 'offer': np.int64(1586),
 'price': np.int64(1764),
 'save': np.int64(1968),
 'high': np.int64(1106),
 'qualiti': np.int64(1815),
 'medic': np.int64(1445),
 'canada': np.int64(296),
 'jone': np.int64(1257),
 'return': np.int64(1906),
 'novemb escapenumb': np.int64(1568),
 'watch': np.int64(2397),
 'alert': np.int64(60),
 'wysak': np.int64(2477),
 'petroleum': np.int64(1678),
 'key': np.int64(1282),
 'sheet': np.int64(2049),
 'sign': np.int64(2062),
 'european': np.int64(853),
 'commiss': np.int64(430),
 'ba': np.int64(157),
 'centr': np.int64(332),
 'wind': np.int64(2437),
 'size': np.int64(2074),
 'matter': np.int64(1430),
 'structur': np.int64(2168),
 'invest': np.int64(1218),
 'issu': np.int64(1230),
 'govern': np.int64(1052),
 'polici': np.int64(1728),
 'negoti': np.int64(1532),
 'techno': np.int64(2222),
 'ogi': np.int64(1591),
 'relat': np.int64(1868),
 'mw': np.int64(1512),
 'po': np.int64(1725),
 'green': np.int64(1059),
 'nearli': np.int64(1528),
 'electr': np.int64(701),
 'mi': np.int64(1458),
 'found': np.int64(995),
 'renew': np.int64(1878),
 'construct': np.int64(472),
 'innov': np.int64(1195),
 'creation': np.int64(521),
 'strategi': np.int64(2160),
 'research': np.int64(1890),
 'capabl': np.int64(302),
 'partner': np.int64(1647),
 'countri': np.int64(509),
 'organ': np.int64(1615),
 'whose': np.int64(2429),
 'goal': np.int64(1044),
 'develop': np.int64(615),
 'fuel': np.int64(1011),
 'site': np.int64(2071),
 'air': np.int64(56),
 'produc': np.int64(1782),

In [10]:
# Dependent Feature
y = pd.get_dummies(messages['label'][:500])

In [11]:
y

       Ham   Spam
0    False   True
1     True  False
2    False   True
3    False   True
4     True  False
..     ...    ...
495   True  False
496  False   True
497   True  False
498   True  False
499   True  False

[500 rows x 2 columns]

In [12]:
y = y.iloc[:,1].values #Taking either one column will do the job for considering o/p

In [13]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [15]:
from sklearn.naive_bayes import MultinomialNB

In [16]:
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [17]:
y_pred = spam_detect_model.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score, classification_report

In [19]:
accuracy_score(y_test,y_pred)

0.85

In [ ]:
print(classification_report(y_test,y_pred)) #to check if the data is balanced or not

              precision    recall  f1-score   support

       False       0.80      0.94      0.87        52
        True       0.92      0.75      0.83        48

    accuracy                           0.85       100
   macro avg       0.86      0.85      0.85       100
weighted avg       0.86      0.85      0.85       100