In [1]:
import pandas as pd
messages = pd.read_csv(r'Datasets/dataset.csv')
messages.head()

  label                                               text
0  Spam  viiiiiiagraaaa\nonly for the ones that want to...
1   Ham  got ice thought look az original message ice o...
2  Spam  yo ur wom an ne eds an escapenumber in ch ma n...
3  Spam  start increasing your odds of success & live s...
4   Ham  author jra date escapenumber escapenumber esca...

In [2]:
# Data Cleaning and Preprocessing
import re
import nltk

In [3]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

In [4]:
corpus=[]
for i in range(len(messages[:500])):
    review = re.sub('[^a-zA-Z]',' ',messages['text'][i])
    review = review.lower()
    review = review.split()
    review = [wl.lemmatize(word,pos="n") for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [5]:
corpus

['viiiiiiagraaaa one want make scream prodigy scrawny crow define upgrade spongy balboa dither moiseyev schumann variegate ponce bernie cox angeles impassive circulate impend miscellany chalkboard whizzing pend armenian cutlet waring makeshift fletch dispel crest cadet dovetail rapprochement gerry bayreuth selectman wilmington tuttle alchemy itt bullyboy caan',
 'got ice thought look az original message ice operation mailto iceoperations intcx com sent friday october escapenumber escapenumber escapenumber escapenumber pm subject escapelong amended participant agreement dear participant receiving email identified company user administrator legal counsel signatory escapelong participant agreement serf notice intercontinentals intent amend agreement effective december escapenumber escapenumber relevant documentation attached includes contact information question thank escapelong inc',
 'yo ur wom ne ed escapenumber ch n b e th n f h er le arn h ow tu rn f ific ati ons escapelong dy international export ltd st regina escapenumber belize city belize escapelong',
 'start increasing odds success live sexually healthy easy imperceptible take take candy become ready hour love modern safe way cover shame minute wait fda approved soft tab order packaged discreetly privacy protection r emove',
 'author jra date escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber fri escapenumber jun escapenumber new revision escapenumber websvn http websvn samba org cgi bin viewcvs cgi view rev root samba rev escapenumber log first part patch make apple life easier two stage make easy review context switching must look like gain root sys setgroups ngroups group become id uid gid arrange order three call always seen together next turn function jeremy modified branch samba escapenumber escapenumber source smbd sec ctx c branch samba escapenumber escapenumber escapenumber source smbd sec ctx c changeset modified branch samba escapenumber escapenumber source smbd sec ctx c branch samba escapenumber escapenumber source smbd sec ctx c escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber utc rev escapenumber branch samba escapenumber escapenumber source smbd sec ctx c escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber utc rev escapenumber escapenumber escapenumber escapenumber escapenumber debug nt user token dbgc class escapenumber token debug unix user token dbgc class escapenumber uid gid ngroups group start context switch gain root ifdef setgroups sys setgroups ngroups group endif become id uid gid end context switch ctx p ut ngroups ngroups escapenumber escapenumber escapenumber escapenumber ctx p token null become id uid gid ctx p ut uid uid ctx p ut gid gid escapenumber escapenumber escapenumber escapenumber sec ctx stack ndx gain root prev ctx p sec ctx stack sec ctx stack ndx start context switch gain root ifdef setgroups sys setgroups prev ctx p ut ngroups prev ctx p ut group endif become id prev ctx p ut uid prev ctx p ut gid end context switch update current user stuff modified branch samba escapenumber escapenumber escapenumber source smbd sec ctx c branch samba escapenumber escapenumber escapenumber source smbd sec ctx c escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber utc rev escapenumber branch samba escapenumber escapenumber escapenumber source smbd sec ctx c escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber utc rev escapenumber escapenumber escapenumber escapenumber escapenumber debug nt user token dbgc class escapenumber token debug unix user token dbgc class escapenumber uid gid ngroups group start context switch gain root ifdef setgroups sys setgroups ngroups group endif become id uid gid end context switch ctx p ut ngroups ngroups escapenumber escapenumber escapenumber escapenumber ctx p token null become id uid gid ctx p ut uid uid ctx p ut gid gid escapenumber escapenumber escapenumber escapenumber sec ctx stack ndx gain root prev ctx p sec ctx stack sec ctx stack ndx start context switch gain root ifdef setgroups sys setgroups prev ctx p ut ngroups prev ctx p ut group endif become id prev ctx p ut uid prev ctx p ut gid end context switch update current user stuff',
 'img src escapenumberd http loan co kr img email imgescapenumber gif width escapenumberd escapenumber height escapenumberd escapenumber border escapenumberd escapenumber img src escapenumberd http loan co kr img email imgescapenumber gif width escapenumberd escapenumber height escapenumberd escapenumber border escapenumberd escapenumber img src escapenumberd http loan co kr img email imgescapenumber gif width escapenumberd escapenumber height escapenumberd escapenumber border escapenumberd escapenumber img src escapenumberd http loan co kr img email imgescapenumber gif width escapenumberd escapenumber height escapenumberd escapenumber border escapenumberd escapenumber hkxtattw x ikybkwdowkikjgzgznk ybreilxqd qfr rrpcckwlipgog',
 'attached weekly deal report lex carroll enron east power marketing inc midwest origination',
 'version created earlier afternoon using ena short form bilateral confidentiality agreement travis c mccullough enron north america corp escapenumber smith street eb escapenumber houston texas escapenumber phone escapenumber escapenumber escapenumber fax escapenumber escapenumber escapenumber',
 'pulp writing printing paper escapenumber escapenumber escapenumber welcome enron pulp writing printing paper news service daily mailing brings recent news headline right inbox may also receive daily service specific following area escapenumber recovered container packaging escapenumber newsprint escapenumber lumber join list click comment feedback simply reply email would like unsubscribe pulp writing printing paper news service please scroll bottom email instruction thanks enjoy content carter holt harvey post huge net loss march september period wausau mosinee paper report escapenumberq earnings escapenumber potlatch citing poor market condition report third quarter loss buckeye break even third quarter escapenumber sale drop domtar report net quarterly sale rise escapenumber escapenumber billion net earnings plummet georgia pacific report third quarter earnings drop sale increase metsaliitto pulp mill project latvia may fall striking union lash finch pruyn set talk n mill pennsylvania center receives escapenumber escapenumber toward printing industry pollution reduction harris group add chuck schultz lead midwest forest industry team carter holt harvey post huge net loss march september period escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber agence france presse wellington oct escapenumber escapenumber agence france presse new zealand largest forest product company carter holt harvey posted net loss escapenumber million new zealand escapenumber escapenumber million dollar first half year said wednesday story top page wausau mosinee paper report escapenumberq earnings escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber bw mosinee wi business wire october escapenumber escapenumber wausau mosinee paper corporation nyse wmo news today announced third quarter net earnings escapenumber escapenumber million escapenumber escapenumber per share escapenumber percent escapenumber escapenumber million escapenumber escapenumber per share prior year sharply net income escapenumber escapenumber million escapenumber escapenumber per share second quarter escapenumber third quarter escapenumber earnings included stock incentive credit escapenumber escapenumber per share compared credit less escapenumber escapenumber per share period last year expense escapenumber escapenumber per share second quarter escapenumber story top page potlatch citing poor market condition report third quarter loss escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber bw spokane wash oct escapenumber escapenumber business wire press release potlatch corporation nyse pch today reported poor market condition product substantially higher intere story top page buckeye break even third quarter escapenumber sale drop escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber bw memphis tenn oct escapenumber escapenumber press release buckeye technology inc today announced net income july september escapenumber quarter break even estimated september escapenumber earnings warning buckeye income cumulative effect change accounting escapenumber escapenumber million quarter last year net sale escapenumber escapenumber million quarter ended escapenumber quarter last year story top page domtar report net quarterly sale rise escapenumber escapenumber billion net earnings plummet escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber prnewswire montreal oct escapenumber escapenumber press release domtar inc today announced net earnings escapenumber million escapenumber escapenumber per common share third quarter escapenumber compared escapenumber million escapenumber escapenumber per common share corresponding period escapenumber operating profit reached escapenumber million compared escapenumber million third quarter escapenumber net sale almost escapenumber escapenumber billion versus escapenumber million period last year story top page georgia pacific report third quarter earnings drop sale increase escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber prnewswire atlanta oct escapenumber escapenumber press release georgia pacific corp nyse gp news today reported third quarter escapenumber income continuing operation escapenumber million escapenumber cent diluted earnings per share one time loss compared income continuing operation escapenumber million escapenumber cent diluted earnings per share period last year company incurred one time escapenumber million pre tax loss escapenumber million tax loss escapenumber escapenumber diluted loss per share sale portion pulp paper facility domtar inc escapenumber escapenumber billion resulting third quarter escapenumber loss continuing operation escapenumber million escapenumber cent diluted loss per share story top page metsaliitto pulp mill project latvia may fall escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber helsingin sanomat oct escapenumber escapenumber helsingin sanomat large new pulp mill planned latvia allowed fell tree forest owned latvian state say latvian minister agriculture atis slakteris announcement mean project joint undertaking finnish forest company mets liitto swedish forest company dra latvian state may realised project would cost fim escapenumber escapenumber million u escapenumber million latvian state prepared provide guarantee supply raw material mets liitto satisfied guarantee story top page striking union lash finch pruyn set talk n mill escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber prnewswire glen fall n oct escapenumber escapenumber press release union representing striking finch pruyn worker today lashed finch pruyn letter company sent escapenumber hourly employee announcing permanently replacing worker strike since june escapenumber story top page pennsylvania center receives escapenumber escapenumber toward printing industry pollution reduction escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber prnewswire pennsylvania department environmenal protection secretary announces escapenumber escapenumber electrotechnology application center northampton community college harrisburg pa oct escapenumber escapenumber p story top page harris group add chuck schultz lead midwest forest industry team escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber press release seattle oct escapenumber escapenumber press release consulting engineering firm harris group inc added charles chuck schultz vice president forest industry midwest region w story top page unsubscribe pulp writing printing paper news click unsubscribe simply send corresponding email news report copyrighted respective author powered forestweb',
 'stefan metze metzmacher writes stefan metze metzmacher schrieb derrell lipman unwireduniverse com schrieb stefan metze metzmacher writes seems revision escapenumber merged branch http websvn samba org cgi bin viewcvs cgi rev escapenumber view rev sorry think merged sambaescapenumber branch occur code used sambaescapenumber maybe better move sambaescapenumber instead libreplace libreplace provide replacement readahead change merged libreplace sambaescapenumber problem intended solve existing readahead function header declares would exist much sambaescapenumber sambaescapenumber even nothing sambaescapenumber currently us readahead please go ahead merge current work also configure test added patch hi derell know initial problem test readahead function configure sambaescapenumber test prototype also really belongs sambaescapenumber exactly lot function sambaescapenumber configure include includes h ok attempt keep sambaescapenumber sambaescapenumber libreplace derrell',
 'hey life sound horribly busy figured worry thought get thing moving since officially replaced announced direct report london fernley sure spoken anxious put announcement enron europe phillip lord leaving melissa stepping replace u since phillip already place go would nice could least say going north america energy ops something even detail worked sure want come meet commercial customer also never met delainey think maybe knowing frevert well enough planning come november first half work europe plan coordinate brent wes group frevert maybe meet people would love discus monday fine sure today another crazy day know review john sherriff put per review per day penalty dept head review done august th course holiday week day review hopefully help direct report problem talk today good weekend beth enron capital trade resource corp sally beck beth apollo lon ect ect cc subject stuff crazy week pm finished project delainey got noon today cancelled everything calendar immersed ever since patti gave message home number around today leaving apologized giving earlier however given immediate project think could called london time think e mail much better still really crunched tomorrow morning mid year review must completed time ena office chair staff meeting tomorrow big push percentage completion rate ena meeting two week ago unfinished review mine give direct report killer wrote three last night tyler went bed finished gave three review morning write tonight deliver tomorrow morning try call way office tomorrow morning car miss late afternoon houston time could call next week shape much better definitely interested continuing conversation would love involved operation either catch car tomorrow morning talk monday',
 'think firewall would catch email freak original message chad knipe mailto knipeescapenumber msn com sent tuesday february escapenumber escapenumber escapenumber escapenumber pm chet fenner feder erik wollam corrier cox internet com c r zander att net joe park john chamber brian constantine c r zander subject location man night open e mail jerky entitled monster facial blasted think firewall would catch original message fenner chet sent tuesday february escapenumber escapenumber escapenumber escapenumber pm feder erwollam corrier cox internet com c k fenner chet c r zander att net joe park john chamber bisys com brianc c r zander subject location man night either way sound like dealing w axis evil restaurant chain guy let admit old get much except zander cause hotty really care food meet gold cup original message feder mailto lawfeder msn com sent tuesday february escapenumber escapenumber escapenumber escapenumber pm erwollam corrier cox internet com c k chet fenner c r zander att net joe park john chamber bisys com brianc c r zander subject location man night as grape see monkey eats grape especially airline drive nice part town hey new al qaeda restaurant telephone road heard good sleeper cell chili hhmmm hmmm good splash taliban relish original message erik wollam sent tuesday february escapenumber escapenumber escapenumber escapenumber pm corrier cox internet com knipeescapenumber msn com chet fenner bmc com c r zander att net joe park enron com john chamber bisys com brianc saltgrass com lawfeder msn com c r zander worldnet att net subject location man night plan thursday escapenumber escapenumber escapenumber restraunt idenitified z pig please provide direction time escapenumber escapenumber e brian constantine erik wollam subject man night date wed escapenumber feb escapenumber escapenumber escapenumber escapenumber escapenumber horrible liquid pudding accompanied incessant stomach cramp fever general malaise last week along w as grape needless say unavailable comment however back full health grape vanished would love men vote go new secret dive zander howling called tampico seafood mexican seafood type joint airline drive close farmer market z say unfuckinbelievable im original message erik wollam mailto erwollam hotmail com sent wednesday february escapenumber escapenumber escapenumber escapenumber pm bcorrier cox internet com knipeescapenumber msn com chet fenner bmc com c r zander att net joe park enron com john chamber bisys com brian constantine lawfeder msn com c r zander worldnet att net subject man night men hunting season working season email thread gone one talk one another wrong therefor propose man night february escapenumberth escapenumber location yet determined tony mexican food ella e chat friend online try msn messenger http messenger msn com msn photo easiest way share print photo http photo msn com support worldwide aspx',
 'luckyday lottery international international promotion prize award dept website www luckyday nl ref mli escapenumber ilgiescapenumber escapenumber batch ipd escapenumber escapenumber ptnl sir madam pleased inform result lottery winner international program held escapenumberth july escapenumber e mail address attached ticket number escapenumber escapenumber serial number escapenumber escapenumber drew lucky number escapenumber escapenumber escapenumber escapenumber escapenumber escapenumber consequently escapenumberrd category therefore approved sum pay u escapenumber escapenumber six hundred twenty three thousand united state dollar congratulation due mix number name ask keep winning information confidential till claim processed prize money remitted part security proto col avoid double claiming unwarranted abuse program participant participant selected computer ballot system drawn escapenumber escapenumber escapenumber company escapenumber escapenumber escapenumber individual email address name world promotional program take place annually hope part winning take part next year usdescapenumber million international lottery file claim please contact fiducial agent dr free de veen fortunegate agency tel escapenumber escapenumber escapenumber escapenumber fax escapenumber escapenumber escapenumber escapenumber e mail escapelong netscape net note winning must claimed later escapenumberth july escapenumber date unclaimed fund included next stake please note order avoid unnecessary delay complication please remember quote reference number batch number correspondence furthermore change address inform agent soon possible congratulation member staff thank part promotional program note anybody age escapenumber automatically disqualified sincerely mr helen van hal lottery coordinator reply email luckyday winningawards nl escapelong netscape net',
 'ti pvc jgjrkwhr j p tc bxff cou roxly exgxj iryqhgno ljpi',

In [30]:
X = corpus
# Dependent Feature
y = pd.get_dummies(messages['label'][:500])

In [31]:
y

       Ham   Spam
0    False   True
1     True  False
2    False   True
3    False   True
4     True  False
..     ...    ...
495   True  False
496  False   True
497   True  False
498   True  False
499   True  False

[500 rows x 2 columns]

In [32]:
y = y.iloc[:,1].values #Taking either one column will do the job for considering o/p

In [33]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

### Create TF-IDF

In [34]:
# Create TF - IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features=2500,ngram_range=(1,2))

In [35]:
# Independent Feature
X_train=cv.fit_transform(X_train).toarray()

In [36]:
X_train

array([[0.        , 0.        , 0.06111941, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.13894154, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(400, 2500))

In [37]:
cv.vocabulary_

{'reducing': np.int64(1839),
 'high': np.int64(1078),
 'doctor': np.int64(643),
 'probably': np.int64(1752),
 'medication': np.int64(1406),
 'keep': np.int64(1240),
 'thing': np.int64(2239),
 'check': np.int64(392),
 'natural': np.int64(1479),
 'alternative': np.int64(79),
 'side': np.int64(2055),
 'effect': np.int64(703),
 'escapenumber': np.int64(778),
 'test': np.int64(2228),
 'show': np.int64(2051),
 'ask': np.int64(131),
 'heard': np.int64(1064),
 'yet': np.int64(2494),
 'drug': np.int64(667),
 'like': np.int64(1303),
 'cause': np.int64(337),
 'whole': np.int64(2426),
 'new': np.int64(1502),
 'set': np.int64(2031),
 'problem': np.int64(1753),
 'fact': np.int64(878),
 'common': np.int64(450),
 'question': np.int64(1804),
 'customer': np.int64(548),
 'care': np.int64(327),
 'able': np.int64(2),
 'taking': np.int64(2202),
 'http': np.int64(1113),
 'com': np.int64(432),
 'escapelong': np.int64(773),
 'html': np.int64(1109),
 'yes': np.int64(2492),
 'many': np.int64(1379),
 'get': np.int64(1007),
 'prescription': np.int64(1728),
 'cut': np.int64(549),
 'even': np.int64(843),
 'month': np.int64(1452),
 'let': np.int64(1293),
 'try': np.int64(2307),
 'safe': np.int64(1937),
 'really': np.int64(1826),
 'work': np.int64(2454),
 'offer': np.int64(1546),
 'first': np.int64(939),
 'people': np.int64(1628),
 'respond': np.int64(1890),
 'email': np.int64(715),
 'late': np.int64(1271),
 'sincerely': np.int64(2066),
 'dr': np.int64(660),
 'director': np.int64(635),
 'wish': np.int64(2443),
 'receive': np.int64(1828),
 'heart': np.int64(1066),
 'please': np.int64(1683),
 'go': np.int64(1017),
 'enter': np.int64(754),
 'address': np.int64(28),
 'may': np.int64(1400),
 'write': np.int64(2466),
 'st': np.int64(2122),
 'click': np.int64(418),
 'longer': np.int64(1330),
 'mailing': np.int64(1361),
 'free': np.int64(977),
 'stuff': np.int64(2165),
 'tx': np.int64(2317),
 'escapelong escapelong': np.int64(775),
 'escapelong html': np.int64(777),
 'html escapenumber': np.int64(1110),
 'wish receive': np.int64(2444),
 'please go': np.int64(1687),
 'go http': np.int64(1018),
 'email address': np.int64(716),
 'tx escapenumber': np.int64(2318),
 'david': np.int64(564),
 'going': np.int64(1021),
 'track': np.int64(2278),
 'issue': np.int64(1201),
 'know': np.int64(1254),
 'trying': np.int64(2308),
 'best': np.int64(240),
 'aware': np.int64(163),
 'thanks': np.int64(2236),
 'robert': np.int64(1921),
 'original': np.int64(1582),
 'message': np.int64(1416),
 'sent': np.int64(2017),
 'wednesday': np.int64(2405),
 'january': np.int64(1210),
 'pm': np.int64(1693),
 'sally': np.int64(1942),
 'jones': np.int64(1225),
 'hr': np.int64(1107),
 'subject': np.int64(2166),
 'terminated': np.int64(2225),
 'employee': np.int64(719),
 'benefit': np.int64(220),
 'net': np.int64(1495),
 'team': np.int64(2215),
 'working': np.int64(2456),
 'daily': np.int64(552),
 'individual': np.int64(1155),
 'record': np.int64(1834),
 'well': np.int64(2415),
 'communicate': np.int64(451),
 'much': np.int64(1468),
 'information': np.int64(1160),
 'would': np.int64(2462),
 'happy': np.int64(1056),
 'name': np.int64(1476),
 'help': np.int64(1071),
 'contact': np.int64(486),
 'tell': np.int64(2221),
 'call': np.int64(308),
 'think': np.int64(2240),
 'helped': np.int64(1074),
 'fw': np.int64(990),
 'communication': np.int64(452),
 'note': np.int64(1521),
 'info': np.int64(1158),
 'regarding': np.int64(1843),
 'status': np.int64(2142),
 'key': np.int64(1247),
 'caught': np.int64(336),
 'willing': np.int64(2435),
 'hall': np.int64(1051),
 'bob': np.int64(267),
 'year': np.int64(2490),
 'enron': np.int64(736),
 'made': np.int64(1356),
 'good': np.int64(1023),
 'friend': np.int64(981),
 'time': np.int64(2255),
 'right': np.int64(1909),
 'feeling': np.int64(910),
 'talk': np.int64(2203),
 'several': np.int64(2034),
 'week': np.int64(2408),
 'update': np.int64(2342),
 'outside': np.int64(1587),
 'want': np.int64(2390),
 'whatever': np.int64(2421),
 'hard': np.int64(1057),
 'reason': np.int64(1827),
 'weekly': np.int64(2412),
 'reminder': np.int64(1862),
 'power': np.int64(1714),
 'something': np.int64(2092),
 'passed': np.int64(1617),
 'phone': np.int64(1654),
 'number': np.int64(1531),
 'need': np.int64(1490),
 'money': np.int64(1451),
 'cash': np.int64(332),
 'balance': np.int64(172),
 'plan': np.int64(1672),
 'find': np.int64(934),
 'etc': np.int64(837),
 'major': np.int64(1367),
 'way': np.int64(2399),
 'told': np.int64(2264),
 'one': np.int64(1562),
 'anything': np.int64(108),
 'send': np.int64(2013),
 'necessary': np.int64(1489),
 'form': np.int64(962),
 'ball': np.int64(174),
 'changed': np.int64(386),
 'active': np.int64(19),
 'take': np.int64(2200),
 'lot': np.int64(1344),
 'nothing': np.int64(1523),
 'coming': np.int64(439),
 'charge': np.int64(388),
 'getting': np.int64(1008),
 'done': np.int64(649),
 'sure': np.int64(2188),
 'sense': np.int64(2016),
 'situation': np.int64(2070),
 'could': np.int64(512),
 'lose': np.int64(1340),
 'home': np.int64(1091),
 'car': np.int64(325),
 'red': np.int64(1836),
 'important': np.int64(1138),
 'original message': np.int64(1583),
 'sent wednesday': np.int64(2022),
 'wednesday january': np.int64(2407),
 'january escapenumber': np.int64(1211),
 'escapenumber escapenumber': np.int64(786),
 'escapenumber pm': np.int64(804),
 'terminated employee': np.int64(2226),
 'let know': np.int64(1294),
 'subject fw': np.int64(2167),
 'escapenumber year': np.int64(818),
 'please let': np.int64(1688),
 'news': np.int64(1504),
 'release': np.int64(1855),
 'immediate': np.int64(1131),
 'june': np.int64(1234),
 'essential': np.int64(832),
 'action': np.int64(17),
 'comment': np.int64(441),
 'letter': np.int64(1295),
 'pressure': np.int64(1734),
 'issued': np.int64(1204),
 'license': np.int64(1301),
 'following': np.int64(953),
 'statement': np.int64(2137),
 'today': np.int64(2260),
 'representative': np.int64(1873),
 'nearly': np.int64(1488),
 'three': np.int64(2247),
 'dozen': np.int64(659),
 'member': np.int64(1411),
 'congress': np.int64(475),
 'trade': np.int64(2280),
 'priority': np.int64(1746),
 'watch': np.int64(2395),
 'list': np.int64(1313),
 'available': np.int64(158),
 'www': np.int64(2472),
 'house': np.int64(1100),
 'gov': np.int64(1026),
 'using': np.int64(2354),
 'legal': np.int64(1289),
 'method': np.int64(1419),
 'price': np.int64(1739),
 'generic': np.int64(1004),
 'aid': np.int64(63),
 'world': np.int64(2458),
 'mean': np.int64(1404),
 'place': np.int64(1671),
 'public': np.int64(1790),
 'health': np.int64(1062),
 'commercial': np.int64(445),
 'clear': np.int64(417),
 'saving': np.int64(1960),
 'used': np.int64(2352),
 'access': np.int64(7),
 'medicine': np.int64(1407),
 'designed': np.int64(611),
 'country': np.int64(517),
 'interest': np.int64(1180),
 'big': np.int64(252),
 'developing': np.int64(621),
 'organization': np.int64(1581),
 'property': np.int64(1774),
 'agreement': np.int64(61),
 'released': np.int64(1856),
 'signed': np.int64(2057),
 'growing': np.int64(1038),
 'policy': np.int64(1697),
 'must': np.int64(1472),
 'change': np.int64(385),
 'emerging': np.int64(717),
 'view': np.int64(2379),
 'reduce': np.int64(1837),
 'make': np.int64(1368),
 'widely': np.int64(2431),
 'government': np.int64(1027),
 'damage': np.int64(555),
 'nation': np.int64(1477),
 'commitment': np.int64(447),
 'reputation': np.int64(1876),
 'national': np.int64(1478),
 'project': np.int64(1770),
 'attorney': np.int64(151),
 'washington': np.int64(2394),
 'dc': np.int64(572),
 'office': np.int64(1549),
 'xescapenumber': np.int64(2482),
 'org': np.int64(1577),
 'ip': np.int64(1198),
 'mailman': np.int64(1363),
 'listinfo': np.int64(1316),
 'news release': np.int64(1505),
 'june escapenumber': np.int64(1235),
 'http www': np.int64(1115),
 'office escapenumber': np.int64(1550),
 'mailing list': np.int64(1362),
 'org http': np.int64(1579),
 'mailman listinfo': np.int64(1364),
 'report': np.int64(1868),
 'sea': np.int64(1978),
 'day': np.int64(566),
 'target': np.int64(2207),
 'short': np.int64(2046),
 'term': np.int64(2223),
 'see': np.int64(1994),
 'broker': np.int64(290),
 'escapenumber day': np.int64(783),
 'target price': np.int64(2208),
 'price escapenumber': np.int64(1740),
 'short term': np.int64(2047),
 'hear': np.int64(1063),
 'instruction': np.int64(1171),
 'wise': np.int64(2442),
 'man': np.int64(1373),
 'law': np.int64(1274),
 'knowledge': np.int64(1255),
 'huge': np.int64(1116),
 'special': np.int64(2102),
 'alert': np.int64(69),
 'line': np.int64(1307),
 'technology': np.int64(2217),
 'last': np.int64(1268),
 'use': np.int64(2351),
 'grid': np.int64(1035),
 'deliver': np.int64(592),
 'bit': np.int64(261),
 'speed': np.int64(2107),
 'data': np.int64(557),
 'voice': np.int64(2383),
 'video': np.int64(2378),
 'transmission': np.int64(2293),
 'sector': np.int64(1988),
 'material': np.int64(1394),
 'herein': np.int64(1075),
 'prepared': np.int64(1727),
 'based': np.int64(189),
 'upon': np.int64(2345),
 'reliable': np.int64(1858),
 'guaranteed': np.int64(1044),
 'considered': np.int64(479),
 'opinion': np.int64(1572),
 'contains': np.int64(490),
 'forward': np.int64(966),
 'looking': np.int64(1334),
 'involve': np.int64(1194),
 'risk': np.int64(1914),
 'uncertainty': np.int64(2326),
 'market': np.int64(1384),
 'maker': np.int64(1370),
 'investment': np.int64(1189),
 'banker': np.int64(182),
 'advisor': np.int64(38),
 'analyst': np.int64(92),
 'selling': np.int64(2010),
 'security': np.int64(1991),
 'mentioned': np.int64(1414),
 'advertisement': np.int64(35),
 'near': np.int64(1487),
 'future': np.int64(989),
 'received': np.int64(1829),
 'third': np.int64(2242),
 'party': np.int64(1611),
 'affiliate': np.int64(50),
 'officer': np.int64(1552),
 'also': np.int64(78),
 'buy': np.int64(302),
 'share': np.int64(2039),
 'intend': np.int64(1173),
 'sell': np.int64(2007),
 'profit': np.int64(1765),
 'event': np.int64(845),
 'rise': np.int64(1913),
 'value': np.int64(2365),
 'forward looking': np.int64(967),
 'looking statement': np.int64(1335),
 'risk uncertainty': np.int64(1915),
 'uncertainty could': np.int64(2327),
 'far': np.int64(887),
 'order': np.int64(1576),
 'space': np.int64(2100),
 'billing': np.int64(257),
 'company': np.int64(454),
 'cost': np.int64(511),
 'center': np.int64(349),
 'pipeline': np.int64(1664),
 'ruthann': np.int64(1936),
 'frausto': np.int64(975),
 'service': np.int64(2029),
 'co': np.int64(424),
 'facility': np.int64(877),
 'location': np.int64(1324),
 'cell': np.int64(347),
 'fax': np.int64(892),
 'maria': np.int64(1382),
 'monday': np.int64(1448),
 'november': np.int64(1526),
 'cc': np.int64(340),
 'read': np.int64(1819),
 'thursday': np.int64(2249),
 'dave': np.int64(563),
 'already': np.int64(77),
 'left': np.int64(1288),
 'tracy': np.int64(2279),
 'october': np.int64(1543),
 'importance': np.int64(1137),
 'fyi': np.int64(991),
 'miller': np.int64(1431),
 'attached': np.int64(146),
 'believe': np.int64(218),
 'although': np.int64(80),
 'process': np.int64(1755),
 'tuesday': np.int64(2309),
 'begin': np.int64(213),
 'related': np.int64(1851),
 'asset': np.int64(136),
 'specific': np.int64(2104),
 'looked': np.int64(1333),
 'determined': np.int64(618),
 'houston': np.int64(1101),
 'created': np.int64(527),
 'additional': np.int64(27),
 'file': np.int64(920),
 'needed': np.int64(1491),
 'xl': np.int64(2483),
 'far order': np.int64(888),
 'pipeline company': np.int64(1665),
 'escapenumber fax': np.int64(787),
 'enron com': np.int64(739),
 'sent monday': np.int64(2019),
 'november escapenumber': np.int64(1527),
 'please read': np.int64(1690),
 'sent thursday': np.int64(2020),
 'october escapenumber': np.int64(1544),
 'sent tuesday': np.int64(2021),
 'please call': np.int64(1684),
 'notice': np.int64(1524),
 'san': np.int64(1951),
 'diego': np.int64(625),
 'gas': np.int64(995),
 'electric': np.int64(710),
 'seller': np.int64(2009),
 'energy': np.int64(723),
 'california': np.int64(307),
 'independent': np.int64(1149),
 'system': np.int64(2196),
 'operator': np.int64(1571),
 'exchange': np.int64(855),
 'investigation': np.int64(1187),
 'practice': np.int64(1717),
 'scheduling': np.int64(1969),
 'reporting': np.int64(1871),
 'requirement': np.int64(1882),
 'outage': np.int64(1586),
 'iso': np.int64(1200),
 'scheduled': np.int64(1968),
 'forced': np.int64(959),
 'federal': np.int64(904),
 'regulatory': np.int64(1850),
 'commission': np.int64(446),
 'ferc': np.int64(914),
 'corporation': np.int64(510),
 'proposed': np.int64(1776),
 'filed': np.int64(921),
 'concerning': np.int64(467),
 'effective': np.int64(704),
 'took': np.int64(2267),
 'schedule': np.int64(1967),
 'generating': np.int64(1002),
 'unit': np.int64(2332),
 'thus': np.int64(2250),
 'enable': np.int64(720),
 'provide': np.int64(1783),
 'efficient': np.int64(705),
 'operation': np.int64(1570),
 'wholesale': np.int64(2427),
 'electricity': np.int64(711),
 'inform': np.int64(1159),
 'participant': np.int64(1606),
 'provision': np.int64(1789),
 'procedure': np.int64(1754),
 'posted': np.int64(1707),
 'web': np.int64(2401),
 'site': np.int64(2069),
 'filing': np.int64(922),
 'authority': np.int64(156),
 'greater': np.int64(1031),
 'control': np.int64(500),
 'seeking': np.int64(1997),
 'request': np.int64(1878),
 'less': np.int64(1292),
 'two': np.int64(2313),
 'hour': np.int64(1098),
 'advance': np.int64(33),
 'requested': np.int64(1879),
 'start': np.int64(2130),
 'final': np.int64(923),
 'approval': np.int64(119),
 'immediately': np.int64(1132),
 'prior': np.int64(1745),
 'planned': np.int64(1673),
 'approved': np.int64(120),
 'required': np.int64(1881),
 'within': np.int64(2446),
 'seven': np.int64(2033),
 'revision': np.int64(1907),
 'factor': np.int64(880),
 'consider': np.int64(478),
 'making': np.int64(1371),
 'initial': np.int64(1164),
 'require': np.int64(1880),
 'detailed': np.int64(617),
 'part': np.int64(1605),
 'whether': np.int64(2423),
 'particular': np.int64(1607),
 'operating': np.int64(1569),
 'condition': np.int64(468),
 'impact': np.int64(1133),
 'pg': np.int64(1647),
 'apply': np.int64(116),
 'real': np.int64(1825),
 'generation': np.int64(1003),
 'capability': np.int64(322),
 'affect': np.int64(49),
 'minute': np.int64(1439),
 'complete': np.int64(460),
 'completed': np.int64(461),
 'via': np.int64(2374),
 'mail': np.int64(1358),
 'beginning': np.int64(215),
 'result': np.int64(1894),
 'direct': np.int64(632),
 'greg': np.int64(1033),
 'manager': np.int64(1376),
 'client': np.int64(419),
 'relation': np.int64(1852),
 'owner': np.int64(1593),
 'shall': np.int64(2038),
 'include': np.int64(1142),
 'taken': np.int64(2201),
 'san diego': np.int64(1952),
 'escapenumber new': np.int64(800),
 'forced outage': np.int64(960),
 'energy regulatory': np.int64(727),
 'may escapenumber': np.int64(1402),
 'web site': np.int64(2402),
 'escapenumber hour': np.int64(789),
 'escapenumber minute': np.int64(798),
 'com escapenumber': np.int64(434),
 'escapenumberth': np.int64(830),
 'reservation': np.int64(1885),
 'pulp': np.int64(1795),
 'writing': np.int64(2468),
 'paper': np.int64(1602),
 'welcome': np.int64(2414),
 'recent': np.int64(1831),
 'area': np.int64(123),
 'join': np.int64(1224),
 'feedback': np.int64(907),
 'simply': np.int64(2063),
 'reply': np.int64(1867),
 'unsubscribe': np.int64(2341),
 'enjoy': np.int64(734),
 'content': np.int64(491),
 'carter': np.int64(330),
 'post': np.int64(1706),
 'loss': np.int64(1342),
 'march': np.int64(1380),
 'september': np.int64(2025),
 'period': np.int64(1639),
 'earnings': np.int64(677),
 'poor': np.int64(1699),
 'quarter': np.int64(1802),
 'break': np.int64(282),
 'sale': np.int64(1941),
 'drop': np.int64(665),
 'billion': np.int64(258),
 'increase': np.int64(1147),
 'fall': np.int64(881),
 'union': np.int64(2330),
 'toward': np.int64(2276),
 'industry': np.int64(1156),
 'harris': np.int64(1059),
 'group': np.int64(1037),
 'add': np.int64(24),
 'chuck': np.int64(404),
 'lead': np.int64(1278),
 'oct': np.int64(1541),
 'largest': np.int64(1266),
 'product': np.int64(1759),
 'million': np.int64(1432),
 'dollar': np.int64(645),
 'half': np.int64(1050),
 'said': np.int64(1938),
 'story': np.int64(2152),
 'top': np.int64(2269),
 'page': np.int64(1598),
 'wi': np.int64(2429),
 'business': np.int64(299),
 'announced': np.int64(99),
 'per': np.int64(1629),
 'percent': np.int64(1632),
 'income': np.int64(1146),
 'second': np.int64(1984),
 'included': np.int64(1143),
 'stock': np.int64(2147),
 'credit': np.int64(531),
 'expense': np.int64(862),
 'press': np.int64(1732),
 'reported': np.int64(1869),
 'higher': np.int64(1079),
 'inc': np.int64(1140),
 'july': np.int64(1231),
 'estimated': np.int64(835),
 'warning': np.int64(2393),
 'accounting': np.int64(10),
 'ended': np.int64(722),
 'almost': np.int64(75),
 'atlanta': np.int64(143),
 'corp': np.int64(507),
 'continuing': np.int64(497),
 'cent': np.int64(348),
 'pre': np.int64(1719),
 'tax': np.int64(2209),
 'portion': np.int64(1701),
 'resulting': np.int64(1895),
 'large': np.int64(1264),
 'fell': np.int64(911),
 'tree': np.int64(2299),
 'owned': np.int64(1592),
 'state': np.int64(2136),
 'say': np.int64(1962),
 'announcement': np.int64(100),
 'guarantee': np.int64(1043),
 'supply': np.int64(2186),
 'since': np.int64(2065),
 'department': np.int64(597),
 'protection': np.int64(1779),
 'secretary': np.int64(1986),
 'application': np.int64(114),
 'community': np.int64(453),
 'pa': np.int64(1596),
 'seattle': np.int64(1981),
 'firm': np.int64(938),
 'added': np.int64(25),
 'charles': np.int64(389),
 'vice': np.int64(2376),
 'president': np.int64(1731),
 'region': np.int64(1844),
 'author': np.int64(155),
 'would like': np.int64(2463),
 'market condition': np.int64(1385),
 'third quarter': np.int64(2243),
 'quarter escapenumber': np.int64(1803),
 'escapenumber billion': np.int64(780),
 'oct escapenumber': np.int64(1542),
 'escapenumber million': np.int64(797),
 'story top': np.int64(2153),
 'top page': np.int64(2270),
 'million escapenumber': np.int64(1434),
 'escapenumber per': np.int64(801),
 'per share': np.int64(1631),
 'escapenumber percent': np.int64(802),
 'last year': np.int64(1270),
 'press release': np.int64(1733),
 'september escapenumber': np.int64(2026),
 'escapenumber cent': np.int64(781),
 'time escapenumber': np.int64(2257),
 'vice president': np.int64(2377),
 'ready': np.int64(1824),
 'electronic': np.int64(712),
 'pay': np.int64(1624),
 'bank': np.int64(178),
 'account': np.int64(9),
 'easy': np.int64(681),
 'fast': np.int64(890),
 'spent': np.int64(2108),
 'link': np.int64(1309),
 'unless': np.int64(2338),
 'default': np.int64(589),
 'stay': np.int64(2143),
 'detail': np.int64(615),
 'asp': np.int64(133),
 'bank account': np.int64(179),
 'please click': np.int64(1685),
 'phone escapenumber': np.int64(1655),
 'please contact': np.int64(1686),
 'corp enron': np.int64(508),
 'ad': np.int64(22),
 'michael': np.int64(1422),
 'taylor': np.int64(2210),
 'water': np.int64(2396),
 'international': np.int64(1183),
 'hiv': np.int64(1085),
 'base': np.int64(188),
 'de': np.int64(573),
 'tel': np.int64(2218),
 'dear': np.int64(578),
 'sir': np.int64(2068),
 'batch': np.int64(193),
 'selected': np.int64(2003),
 'board': np.int64(266),
 'social': np.int64(2083),
 'research': np.int64(1884),
 'development': np.int64(622),
 'according': np.int64(8),
 'estimate': np.int64(834),
 'different': np.int64(629),
 'woman': np.int64(2452),
 'among': np.int64(87),
 'child': np.int64(399),
 'end': np.int64(721),
 'became': np.int64(209),
 'around': np.int64(127),
 'become': np.int64(210),
 'total': np.int64(2273),
 'live': np.int64(1320),
 'still': np.int64(2146),
 'remains': np.int64(1860),
 'thought': np.int64(2245),
 'past': np.int64(1620),
 'men': np.int64(1413),
 'user': np.int64(2353),
 'come': np.int64(438),
 'sex': np.int64(2035),
 'likely': np.int64(1304),
 'chance': np.int64(384),
 'provided': np.int64(1785),
 'easily': np.int64(680),
 'often': np.int64(1554),
 'seen': np.int64(2000),
 'war': np.int64(2392),
 'conflict': np.int64(474),
 'thousand': np.int64(2246),

In [38]:
X_test = cv.transform(X_test).toarray()
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 2500))

### ML Model Training

In [39]:
from sklearn.naive_bayes import MultinomialNB

In [40]:
spam_detect_model = MultinomialNB().fit(X_train,y_train)

In [41]:
y_pred = spam_detect_model.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score, classification_report

In [43]:
accuracy_score(y_test,y_pred)

0.84

In [44]:
print(classification_report(y_test,y_pred)) #to check if the data is balanced or not

              precision    recall  f1-score   support

       False       0.85      0.85      0.85        55
        True       0.82      0.82      0.82        45

    accuracy                           0.84       100
   macro avg       0.84      0.84      0.84       100
weighted avg       0.84      0.84      0.84       100